# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blackstone Trial Analytics
email: contact@blackstonetrial.com
phone: 703.537.0731
address: 4023 Chain Bridge Road, Suite 11, Fairfax, VA 22030
description: > # this means to ignore newlines until "baseurl:"
  A Win-rate based Northern Virginia attorney referrals for defendants and consulting for law firms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blackstonetrial.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
